// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5bP96ZMVDIp2MOQRTdbKLWYuR7BaBzTw',
    appId: '1:1037592356878:web:b877c5a211e5081fcaf45f',
    messagingSenderId: '1037592356878',
    projectId: 'receptapp-6592d',
    authDomain: 'receptapp-6592d.firebaseapp.com',
    storageBucket: 'receptapp-6592d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC_5hSeAPZlN1_cj7nzMHk27AhDBvUKJ4',
    appId: '1:1037592356878:android:f49f73d77d79ef4bcaf45f',
    messagingSenderId: '1037592356878',
    projectId: 'receptapp-6592d',
    storageBucket: 'receptapp-6592d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMOcBgkpTAP1LJl3loYWhSWKjRI8PpqnM',
    appId: '1:1037592356878:ios:330e7fdcaf640e9ccaf45f',
    messagingSenderId: '1037592356878',
    projectId: 'receptapp-6592d',
    storageBucket: 'receptapp-6592d.appspot.com',
    iosClientId: '1037592356878-d6daikkahqn6conn5h61n9c0uqime7kt.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMOcBgkpTAP1LJl3loYWhSWKjRI8PpqnM',
    appId: '1:1037592356878:ios:330e7fdcaf640e9ccaf45f',
    messagingSenderId: '1037592356878',
    projectId: 'receptapp-6592d',
    storageBucket: 'receptapp-6592d.appspot.com',
    iosClientId: '1037592356878-d6daikkahqn6conn5h61n9c0uqime7kt.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipeApp',
  );
}
